# GENERATED BY `retheme` — do not edit by hand.
# Shell-consumable palette. Source this from scripts:  . ~/.local/share/rice/colors.sh

RICE_SOURCE='{{colors.source_color.default.hex}}'
RICE_MODE='{{mode}}'

RICE_PRIMARY='{{colors.primary.default.hex}}'
RICE_ON_PRIMARY='{{colors.on_primary.default.hex}}'
RICE_PRIMARY_CONTAINER='{{colors.primary_container.default.hex}}'
RICE_PRIMARY_FIXED='{{colors.primary_fixed.default.hex}}'
RICE_PRIMARY_FIXED_DIM='{{colors.primary_fixed_dim.default.hex}}'

RICE_SECONDARY='{{colors.secondary.default.hex}}'
RICE_TERTIARY='{{colors.tertiary.default.hex}}'
RICE_ERROR='{{colors.error.default.hex}}'
RICE_RED='{{colors.rice_red.default.hex}}'
RICE_GREEN='{{colors.rice_green.default.hex}}'
RICE_YELLOW='{{colors.rice_yellow.default.hex}}'

RICE_SURFACE='{{colors.surface.default.hex}}'
RICE_SURFACE_LOWEST='{{colors.surface_container_lowest.default.hex}}'
RICE_SURFACE_LOW='{{colors.surface_container_low.default.hex}}'
RICE_SURFACE_CONTAINER='{{colors.surface_container.default.hex}}'
RICE_SURFACE_HIGH='{{colors.surface_container_high.default.hex}}'
RICE_SURFACE_HIGHEST='{{colors.surface_container_highest.default.hex}}'

RICE_ON_SURFACE='{{colors.on_surface.default.hex}}'
RICE_ON_SURFACE_VARIANT='{{colors.on_surface_variant.default.hex}}'
RICE_OUTLINE='{{colors.outline.default.hex}}'
RICE_OUTLINE_VARIANT='{{colors.outline_variant.default.hex}}'
RICE_INVERSE_SURFACE='{{colors.inverse_surface.default.hex}}'
