-- GENERATED BY `retheme` — do not edit by hand.
-- Source palette: {{colors.source_color.default.hex}}
return {
  source = "{{colors.source_color.default.hex}}",
  mode = "{{mode}}",

  primary = "{{colors.primary.default.hex}}",
  on_primary = "{{colors.on_primary.default.hex}}",
  primary_fixed = "{{colors.primary_fixed.default.hex}}",
  secondary = "{{colors.secondary.default.hex}}",
  tertiary = "{{colors.tertiary.default.hex}}",
  error = "{{colors.error.default.hex}}",
  red = "{{colors.rice_red.default.hex}}",
  green = "{{colors.rice_green.default.hex}}",
  yellow = "{{colors.rice_yellow.default.hex}}",

  surface = "{{colors.surface.default.hex}}",
  surface_lowest = "{{colors.surface_container_lowest.default.hex}}",
  surface_low = "{{colors.surface_container_low.default.hex}}",
  surface_container = "{{colors.surface_container.default.hex}}",
  surface_high = "{{colors.surface_container_high.default.hex}}",

  on_surface = "{{colors.on_surface.default.hex}}",
  on_surface_variant = "{{colors.on_surface_variant.default.hex}}",
  outline = "{{colors.outline.default.hex}}",
  outline_variant = "{{colors.outline_variant.default.hex}}",
}
