# GENERATED BY `retheme` — do not edit by hand.
# Source palette: {{colors.source_color.default.hex}}
#
# Environment for the CLI tools that take colors as env vars rather than config
# files (eza, bat, fzf). Sourced from ~/.bashrc; every block is guarded there,
# so this file is safe to source even if a tool isn't installed.

# bat resolves themes by *filename* (themes/rice.tmTheme), not the <name> key
# inside the plist — so this is lowercase.
export BAT_THEME="rice"

# eza — truecolor SGR triples, palette-driven.
export EZA_COLORS="di=1;38;2;{{colors.primary.default.red}};{{colors.primary.default.green}};{{colors.primary.default.blue}}:\
ex=38;2;{{colors.rice_green.default.red}};{{colors.rice_green.default.green}};{{colors.rice_green.default.blue}}:\
ln=38;2;{{colors.secondary.default.red}};{{colors.secondary.default.green}};{{colors.secondary.default.blue}}:\
ur=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
uw=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
ux=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
ue=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
gr=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
gw=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
gx=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
tr=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
tw=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
tx=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
sn=38;2;{{colors.on_surface_variant.default.red}};{{colors.on_surface_variant.default.green}};{{colors.on_surface_variant.default.blue}}:\
sb=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
da=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
uu=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
gu=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
ga=38;2;{{colors.rice_green.default.red}};{{colors.rice_green.default.green}};{{colors.rice_green.default.blue}}:\
gm=38;2;{{colors.rice_yellow.default.red}};{{colors.rice_yellow.default.green}};{{colors.rice_yellow.default.blue}}:\
gd=38;2;{{colors.rice_red.default.red}};{{colors.rice_red.default.green}};{{colors.rice_red.default.blue}}:\
gv=38;2;{{colors.primary_fixed.default.red}};{{colors.primary_fixed.default.green}};{{colors.primary_fixed.default.blue}}:\
gt=38;2;{{colors.secondary.default.red}};{{colors.secondary.default.green}};{{colors.secondary.default.blue}}:\
gi=38;2;{{colors.outline.default.red}};{{colors.outline.default.green}};{{colors.outline.default.blue}}:\
gc=38;2;{{colors.error.default.red}};{{colors.error.default.green}};{{colors.error.default.blue}}"

# fzf — bg:-1 keeps the terminal's own background showing through.
export FZF_DEFAULT_OPTS="\
--height=45% --layout=reverse --border=rounded --info=inline \
--color=bg+:{{colors.surface_container_high.default.hex}},bg:-1,spinner:{{colors.rice_green.default.hex}},hl:{{colors.tertiary.default.hex}} \
--color=fg:{{colors.on_surface_variant.default.hex}},header:{{colors.tertiary.default.hex}},info:{{colors.outline.default.hex}},pointer:{{colors.primary.default.hex}} \
--color=marker:{{colors.rice_green.default.hex}},fg+:{{colors.on_surface.default.hex}},prompt:{{colors.primary.default.hex}},hl+:{{colors.tertiary.default.hex}} \
--color=border:{{colors.outline_variant.default.hex}}"
